// HornbillPlatform Model V2: one habitat model per species, combined display.
(function(){
'use strict';
const CFG={seed:2569,thin:0.025,bg:1200,minP:20,fit:{lr:.22,iters:220,l2:.025},paths:{temp:'assets/rasters/mean_temp_annual_tmd_1991-2020.tif',rainfall:'assets/rasters/rainfall_annual_tmd_1991-2020.tif',dust:'assets/rasters/pm25_regional_2014-2024.tif',forest:'assets/rasters/forest_cover_2025_hansen.tif'}};
const S={rasters:null,models:[],map:null,overlay:null,view:'rich-current',species:null,scenario:{year:2030,temp:0,rainfall:0,dust:0},grid:null,ran:false};
function rng(seed){let a=seed>>>0;return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function hash(s){let h=2166136261>>>0;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function sig(z){return z>35?1:z<-35?0:1/(1+Math.exp(-z))}
function ring(lat,lon,r){let ins=false;for(let i=0,j=r.length-1;i<r.length;j=i++){const xi=r[i][0],yi=r[i][1],xj=r[j][0],yj=r[j][1];if(((yi>lat)!=(yj>lat))&&(lon<(xj-xi)*(lat-yi)/((yj-yi)||1e-12)+xi))ins=!ins}return ins}
function inside(lat,lon,g){g=g&&g.type==='Feature'?g.geometry:g;if(!g)return true;if(g.type==='Polygon')return ring(lat,lon,g.coordinates[0]);if(g.type==='MultiPolygon')return g.coordinates.some(p=>ring(lat,lon,p[0]));return true}
function clean(sp){const raw=(sp.points||[]).filter(p=>Array.isArray(p)&&isFinite(p[0])&&isFinite(p[1]));const u=[],seen=new Set;raw.forEach(p=>{const k=p[0].toFixed(6)+','+p[1].toFixed(6);if(!seen.has(k)){seen.add(k);u.push(p)}});const thai=u.filter(p=>inside(p[0],p[1],THAILAND_BOUNDARY)),thin=[],cells=new Set;thai.forEach(p=>{const k=Math.floor(p[0]/CFG.thin)+':'+Math.floor(p[1]/CFG.thin);if(!cells.has(k)){cells.add(k);thin.push(p)}});return{raw:raw.length,unique:u.length,thai:thai.length,points:thin}}
function stats(rows){return rows[0].map((_,j)=>{const v=rows.map(r=>r[j]),m=v.reduce((a,b)=>a+b,0)/v.length,sd=Math.sqrt(v.reduce((a,b)=>a+(b-m)*(b-m),0)/v.length)||1;return{m,sd}})}
const z=(st,r)=>r.map((v,j)=>(v-st[j].m)/st[j].sd);
function fit(X,y,o){const nf=X[0].length,w=Array(nf).fill(0);let b=0;for(let it=0;it<o.iters;it++){const gw=Array(nf).fill(0);let gb=0;for(let i=0;i<X.length;i++){let s=b;for(let j=0;j<nf;j++)s+=w[j]*X[i][j];const e=sig(s)-y[i];for(let j=0;j<nf;j++)gw[j]+=e*X[i][j];gb+=e}for(let j=0;j<nf;j++)w[j]-=o.lr*(gw[j]/X.length+o.l2*w[j]);b-=o.lr*gb/X.length}return{w,b}}
function pred(m,r){let s=m.b;for(let j=0;j<r.length;j++)s+=m.w[j]*r[j];return sig(s)}
function auc(sc,y){const ord=sc.map((_,i)=>i).sort((a,b)=>sc[a]-sc[b]),rank=Array(sc.length);let i=0;while(i<ord.length){let j=i+1;while(j<ord.length&&sc[ord[j]]===sc[ord[i]])j++;const av=(i+1+j)/2;for(let k=i;k<j;k++)rank[ord[k]]=av;i=j}let np=0,nn=0,sr=0;y.forEach((v,i)=>{if(v){np++;sr+=rank[i]}else nn++});return np&&nn?(sr-np*(np+1)/2)/(np*nn):null}
function shuffle(n,R){const a=Array.from({length:n},(_,i)=>i);for(let i=n-1;i>0;i--){const j=Math.floor(R()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function cv(X,y,seed){const o=shuffle(X.length,rng(seed)),fs=Math.ceil(X.length/5),as=[];for(let f=0;f<5;f++){const t=new Set(o.slice(f*fs,(f+1)*fs)),tx=[],ty=[],vx=[],vy=[];for(let i=0;i<X.length;i++)t.has(i)?(vx.push(X[i]),vy.push(y[i])):(tx.push(X[i]),ty.push(y[i]));if(tx.length&&vx.length){const m=fit(tx,ty,CFG.fit),a=auc(vx.map(r=>pred(m,r)),vy);if(a!=null)as.push(a)}}return as.length?as.reduce((a,b)=>a+b,0)/as.length:null}
function threshold(sc,y){let best=.5,bj=-9;for(let t=.15;t<=.85;t+=.01){let tp=0,fn=0,tn=0,fp=0;y.forEach((v,i)=>v?(sc[i]>=t?tp++:fn++):(sc[i]>=t?fp++:tn++));const j=tp/(tp+fn||1)+tn/(tn+fp||1)-1;if(j>bj){bj=j;best=t}}return best}
function perm(X,y,m,base,seed){const R=rng(seed),d=[];for(let j=0;j<X[0].length;j++){const c=X.map(r=>r[j]);for(let i=c.length-1;i>0;i--){const k=Math.floor(R()*(i+1));[c[i],c[k]]=[c[k],c[i]]}const a=auc(X.map((r,i)=>pred(m,r.map((v,k)=>k===j?c[i]:v))),y);d.push(Math.max(0,(base||.5)-(a||.5)))}const s=d.reduce((a,b)=>a+b,0);return s?d.map(v=>100*v/s):d.map(()=>100/d.length)}
function sample(lat,lon,ids){const a=[];for(const id of ids){const v=sampleRasterAt(S.rasters[id],lat,lon);if(v===null||!isFinite(v))return null;a.push(v)}return a}
function background(ids,pres,seed){const R=rng(seed),r=S.rasters[ids[0]],[w,s,e,n]=r.bbox,used=new Set(pres.map(p=>Math.floor(p[0]/CFG.thin)+':'+Math.floor(p[1]/CFG.thin))),out=[];let tries=0;while(out.length<CFG.bg&&tries++<CFG.bg*60){const lat=s+R()*(n-s),lon=w+R()*(e-w),k=Math.floor(lat/CFG.thin)+':'+Math.floor(lon/CFG.thin);if(used.has(k)||!inside(lat,lon,THAILAND_BOUNDARY))continue;const v=sample(lat,lon,ids);if(!v)continue;used.add(k);out.push(v)}return out}
function fitSpecies(sp,i){const c=clean(sp),ids=['temp','rainfall','dust','forest'],px=[];c.points.forEach(p=>{const v=sample(p[0],p[1],ids);if(v)px.push(v)});if(px.length<CFG.minP)return{sp,c,error:'Insufficient cleaned points'};const seed=(CFG.seed+hash(sp.id||sp.common||i))>>>0,bg=background(ids,c.points,seed);if(bg.length<CFG.minP)return{sp,c,error:'Insufficient background'};const raw=px.concat(bg),st=stats(raw),X=px.map(r=>z(st,r)).concat(bg.map(r=>z(st,r))),y=Array(px.length).fill(1).concat(Array(bg.length).fill(0)),m=fit(X,y,CFG.fit),sc=X.map(r=>pred(m,r)),base=auc(sc,y),pr=px.map(r=>pred(m,z(st,r)));return{sp,c,ids,st,m,nP:px.length,nB:bg.length,auc:cv(X,y,seed^12345),mean:pr.reduce((a,b)=>a+b,0)/pr.length,thr:threshold(sc,y),imp:perm(X,y,m,base,seed^67890)}}
async function load(){const o={};for(const [id,p] of Object.entries(CFG.paths))o[id]=await fetchGeoTiff(p,p.split('/').pop());return o}
function cell(r,row,col){const [w,s,e,n]=r.bbox;return[n-(row+.5)/r.height*(n-s),w+(col+.5)/r.width*(e-w)]}
function prob(m,lat,lon){const cur=sample(lat,lon,m.ids);if(!cur)return null;const fut=cur.slice();m.ids.forEach((id,j)=>{if(id==='temp')fut[j]+=S.scenario.temp;if(id==='rainfall')fut[j]+=S.scenario.rainfall;if(id==='dust')fut[j]+=S.scenario.dust});return{c:pred(m.m,z(m.st,cur)),f:pred(m.m,z(m.st,fut))}}
function area(r,row){const [w,s,e,n]=r.bbox,lat=n-(row+.5)/r.height*(n-s);return 111.32*((n-s)/r.height)*111.32*Math.cos(lat*Math.PI/180)*((e-w)/r.width)}
function grid(){const r=S.rasters.temp,N=r.width*r.height,good=S.models.filter(m=>!m.error),cr=new Uint8Array(N),fr=new Uint8Array(N),by={};good.forEach(m=>by[m.sp.id]={c:new Float32Array(N),f:new Float32Array(N),a:{stable:0,loss:0,gain:0,current:0,future:0}});for(let row=0;row<r.height;row++){const ar=area(r,row);for(let col=0;col<r.width;col++){const i=row*r.width+col,[lat,lon]=cell(r,row,col);if(!inside(lat,lon,THAILAND_BOUNDARY))continue;for(const m of good){const p=prob(m,lat,lon);if(!p)continue;const b=by[m.sp.id];b.c[i]=p.c;b.f[i]=p.f;const c=p.c>=m.thr,f=p.f>=m.thr;if(c){cr[i]++;b.a.current+=ar}if(f){fr[i]++;b.a.future+=ar}if(c&&f)b.a.stable+=ar;else if(c&&!f)b.a.loss+=ar;else if(!c&&f)b.a.gain+=ar}}}S.grid={r,cr,fr,by}}
function colorRich(v,max){if(!v)return[238,235,226,25];const t=v/Math.max(1,max);return[245-150*t,238-70*t,210-135*t,205].map(Math.round)}
function colorSuit(v){return[245-160*v,240-80*v,220-125*v,210].map(Math.round)}
function img(){const g=S.grid,r=g.r,c=document.createElement('canvas');c.width=r.width;c.height=r.height;const x=c.getContext('2d'),im=x.createImageData(r.width,r.height),max=S.models.filter(m=>!m.error).length,id=S.species||(S.models.find(m=>!m.error)||{}).sp?.id,m=S.models.find(m=>m.sp.id===id);for(let i=0;i<r.width*r.height;i++){let q;if(S.view==='rich-current')q=colorRich(g.cr[i],max);else if(S.view==='rich-future')q=colorRich(g.fr[i],max);else if(S.view==='rich-change'){const d=g.fr[i]-g.cr[i];q=d>0?[62,132,85,210]:d<0?[185,82,67,210]:[210,204,187,70]}else if(S.view==='species-current')q=colorSuit(g.by[id].c[i]);else if(S.view==='species-future')q=colorSuit(g.by[id].f[i]);else{const C=g.by[id].c[i]>=m.thr,F=g.by[id].f[i]>=m.thr;q=C&&F?[184,171,120,180]:C&&!F?[185,82,67,210]:!C&&F?[62,132,85,210]:[0,0,0,0]}const p=i*4;im.data[p]=q[0];im.data[p+1]=q[1];im.data[p+2]=q[2];im.data[p+3]=q[3]}x.putImageData(im,0,0);return c.toDataURL('image/png')}
function mapUpdate(){if(!S.grid)return;const r=S.grid.r,[w,s,e,n]=r.bbox;if(S.overlay)S.map.removeLayer(S.overlay);S.overlay=L.imageOverlay(img(),[[s,w],[n,e]],{opacity:.82}).addTo(S.map)}
function render(){const h=document.getElementById('hbv2-results');if(!S.ran){h.innerHTML='<div class="hbv2-note">Run Model V2 to calculate one independent model per species.</div>';return}const rows=S.models.map(m=>m.error?`<tr><td>${m.sp.common}</td><td colspan="8">${m.error}</td></tr>`:(()=>{const a=S.grid.by[m.sp.id].a,im=Object.fromEntries(m.ids.map((id,j)=>[id,m.imp[j]||0]));return`<tr><td><b>${m.sp.common}</b><br><small>${m.sp.latin||''}</small></td><td>${m.c.raw.toLocaleString()}→${m.c.points.length.toLocaleString()}</td><td>${m.auc==null?'—':m.auc.toFixed(2)}</td><td>${m.mean.toFixed(2)}</td><td>${(im.temp||0).toFixed(0)}%</td><td>${(im.rainfall||0).toFixed(0)}%</td><td>${(im.dust||0).toFixed(0)}%</td><td>${(im.forest||0).toFixed(0)}%</td><td>${Math.round(a.current).toLocaleString()} / ${Math.round(a.future).toLocaleString()}</td></tr>`})()).join('');h.innerHTML=`<div class="hbv2-table-wrap"><table class="hbv2-table"><thead><tr><th>Species</th><th>GBIF raw→cleaned</th><th>CV AUC</th><th>Mean HSI</th><th>Temp</th><th>Rain</th><th>PM2.5</th><th>Forest</th><th>Current / Scenario km²</th></tr></thead><tbody>${rows}</tbody></table></div><div class="hbv2-note">Each hornbill species is modelled independently; the map combines outputs. Scenario values shift the current environmental raster baseline and should not be described as validated future climate projections unless real future rasters are supplied.</div>`}
function status(t){document.getElementById('hbv2-status').textContent=t}
async function runAll(){try{status('Loading environmental rasters…');S.rasters=await load();S.models=[];for(let i=0;i<SPECIES.length;i++){status(`Fitting ${i+1}/${SPECIES.length}: ${SPECIES[i].common}…`);await new Promise(r=>setTimeout(r,10));S.models.push(fitSpecies(SPECIES[i],i))}status('Building current and scenario habitat surfaces…');await new Promise(r=>setTimeout(r,10));grid();S.ran=true;S.species=(S.models.find(m=>!m.error)||{}).sp?.id;const sel=document.getElementById('hbv2-species');sel.innerHTML=S.models.filter(m=>!m.error).map(m=>`<option value="${m.sp.id}">${m.sp.common}</option>`).join('');render();mapUpdate();status('Model V2 complete. Species models are separate; dashboard is combined.')}catch(e){console.error(e);status('Model V2 failed: '+e.message)}}
function ui(){if(document.getElementById('hornbill-model-v2'))return;const app=document.getElementById('app'),w=document.createElement('section');w.id='hornbill-model-v2';w.className='hbv2';w.innerHTML=`<div class="hbv2-head"><div><div class="hbv2-kicker">MODEL V2</div><h2>Species-specific Habitat Suitability + Combined Hornbill Dashboard</h2><p>ศึกษาปัจจัยสิ่งแวดล้อมและพื้นที่เหมาะสมของนกเงือกแต่ละชนิด แต่แสดงผลพร้อมกันทั้งหมด</p></div><button id="hbv2-run">Run Model V2</button></div><div class="hbv2-controls"><label>Scenario year<select id="hbv2-year"><option>2030</option><option>2050</option><option>2070</option></select></label><label>Temperature Δ (°C)<input id="hbv2-temp" type="number" step="0.5" value="0"></label><label>Rainfall Δ (mm)<input id="hbv2-rain" type="number" step="50" value="0"></label><label>PM2.5 Δ (µg/m³)<input id="hbv2-dust" type="number" step="1" value="0"></label><button id="hbv2-apply">Apply scenario</button></div><div id="hbv2-status" class="hbv2-status">Ready.</div><div class="hbv2-grid"><div class="hbv2-card"><div class="hbv2-map-tools"><select id="hbv2-view"><option value="rich-current">Combined: current hornbill richness</option><option value="rich-future">Combined: scenario hornbill richness</option><option value="rich-change">Combined: richness change</option><option value="species-current">Species: current suitability</option><option value="species-future">Species: scenario suitability</option><option value="species-change">Species: stable / loss / gain</option></select><select id="hbv2-species" disabled><option>Run model first</option></select></div><div id="hbv2-map"></div></div><div id="hbv2-results" class="hbv2-card"><div class="hbv2-note">Run Model V2 to calculate one independent model per species.</div></div></div>`;app.insertAdjacentElement('afterend',w);S.map=L.map('hbv2-map',{preferCanvas:true,scrollWheelZoom:true}).setView([13.1,101],5);L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{attribution:'&copy; OpenStreetMap contributors &copy; CARTO',maxZoom:18}).addTo(S.map);const ol=L.geoJSON(THAILAND_BOUNDARY,{style:{color:'#3a4033',weight:1,fill:false}}).addTo(S.map);S.map.fitBounds(ol.getBounds(),{padding:[15,15]});document.getElementById('hbv2-run').onclick=runAll;document.getElementById('hbv2-apply').onclick=()=>{S.scenario={year:+document.getElementById('hbv2-year').value,temp:+document.getElementById('hbv2-temp').value||0,rainfall:+document.getElementById('hbv2-rain').value||0,dust:+document.getElementById('hbv2-dust').value||0};if(S.ran){status('Recomputing scenario…');setTimeout(()=>{grid();render();mapUpdate();status('Scenario updated.')},10)}};document.getElementById('hbv2-view').onchange=e=>{S.view=e.target.value;document.getElementById('hbv2-species').disabled=S.view.startsWith('rich');mapUpdate()};document.getElementById('hbv2-species').onchange=e=>{S.species=e.target.value;mapUpdate()}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ui);else ui();
})();