// Scenario-aware environmental maps for the original student UI.
(function(){
  'use strict';
  const M={main:null,rasters:null,overlay:null,baseline:{temp:null,rainfall:null,dust:null},panel:null,ready:false};
  const oldMap=L.map.bind(L);
  L.map=function(id,opt){const m=oldMap(id,opt);if(id==='leafletMap')M.main=m;return m;};

  function median(a){if(!a.length)return null;a=a.slice().sort((x,y)=>x-y);const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2;}
  function activeTab(){if(document.getElementById('mapTabTemperature')?.classList.contains('active'))return'temp';if(document.getElementById('mapTabRainfall')?.classList.contains('active'))return'rainfall';if(document.getElementById('mapTabDust')?.classList.contains('active'))return'dust';return'distribution';}
  function input(field){const e=document.querySelector(`input[data-onchange="climateAbsolute"][data-field="${field}"]`);return e?Number(e.value):null;}
  function deltas(){const t=input('tempDelta'),r=input('rainfallDelta'),d=input('dustDelta');return{temp:t===null?0:t-M.baseline.temp,rainfall:r===null?0:r-M.baseline.rainfall,dust:d===null?0:d-M.baseline.dust};}

  function insideRing(lat,lon,ring){let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const xi=ring[i][0],yi=ring[i][1],xj=ring[j][0],yj=ring[j][1];if(((yi>lat)!==(yj>lat))&&lon<(xj-xi)*(lat-yi)/((yj-yi)||1e-12)+xi)inside=!inside;}return inside;}
  function inside(lat,lon){const g=typeof THAILAND_BOUNDARY!=='undefined'?THAILAND_BOUNDARY:null;if(!g)return true;const x=g.type==='Feature'?g.geometry:g;if(x.type==='Polygon')return insideRing(lat,lon,x.coordinates[0]);if(x.type==='MultiPolygon')return x.coordinates.some(p=>insideRing(lat,lon,p[0]));return true;}

  function observedMedian(r){const vals=[];SPECIES.forEach(sp=>sp.points.forEach(p=>{const v=sampleRasterAt(r,p[0],p[1]);if(v!==null&&isFinite(v))vals.push(v);}));return median(vals);}
  function shiftedUrl(kind){const src=M.rasters[kind],mapId=kind==='temp'?'temperature':kind,delta=deltas()[kind],band=new Float32Array(src.band.length);let min=Infinity,max=-Infinity;for(let i=0;i<src.band.length;i++){const v=src.band[i];if(src.nodata!==null&&v===src.nodata){band[i]=v;continue;}const nv=v+delta;band[i]=nv;if(nv<min)min=nv;if(nv>max)max=nv;}return renderRasterToDataUrl({...src,band,min,max},RASTER_RAMPS[mapId],THAILAND_BOUNDARY,RASTER_CLASSES[mapId].breaks);}

  function updateMap(){if(!M.ready||!M.main)return;const tab=activeTab();if(M.overlay&&M.main.hasLayer(M.overlay)){M.main.removeLayer(M.overlay);M.overlay=null;}if(tab==='distribution'){updatePanel(false);return;}const r=M.rasters[tab],[w,s,e,n]=r.bbox;M.overlay=L.imageOverlay(shiftedUrl(tab),[[s,w],[n,e]],{opacity:.88,interactive:false}).addTo(M.main);const d=deltas()[tab],note=document.getElementById('mapRealNote');if(note){const name=tab==='temp'?'Temperature':tab==='rainfall'?'Rainfall':'PM2.5',unit=tab==='temp'?'°C':tab==='rainfall'?'mm':'µg/m³';note.textContent=`${name} scenario = current raster ${d>=0?'+':''}${d.toFixed(tab==='rainfall'?0:1)} ${unit}`;}updatePanel(tab==='dust');}

  const REG=[{id:'N',th:'ภาคเหนือ',en:'North',c:'#7a2f91'},{id:'NE',th:'ภาคตะวันออกเฉียงเหนือ',en:'Northeast',c:'#ef7a24'},{id:'C',th:'ภาคกลาง',en:'Central',c:'#d3a91d'},{id:'E',th:'ภาคตะวันออก',en:'East',c:'#78a93f'},{id:'S',th:'ภาคใต้',en:'South',c:'#2b98d1'}];
  function region(lat,lon){if(lat<10.8)return'S';if(lat>=15.4&&lon<101.7)return'N';if(lat>=14&&lon>=101.7)return'NE';if(lat<14.7&&lon>=100.8)return'E';return'C';}
  function calcRegional(){const r=M.rasters.dust,sums={N:0,NE:0,C:0,E:0,S:0},cnt={N:0,NE:0,C:0,E:0,S:0},[w,s,e,n]=r.bbox;for(let row=0;row<r.height;row++){const lat=n-(row+.5)/r.height*(n-s);for(let col=0;col<r.width;col++){const i=row*r.width+col,v=r.band[i];if(!isFinite(v)||(r.nodata!==null&&v===r.nodata))continue;const lon=w+(col+.5)/r.width*(e-w);if(!inside(lat,lon))continue;const id=region(lat,lon);sums[id]+=v;cnt[id]++;}}M.regional=Object.fromEntries(REG.map(x=>[x.id,cnt[x.id]?sums[x.id]/cnt[x.id]:null]));}
  function ensurePanel(){if(M.panel)return;const wrap=document.getElementById('mapWrap');if(!wrap)return;const layout=document.createElement('div');layout.className='map-region-layout';wrap.parentNode.insertBefore(layout,wrap);layout.appendChild(wrap);M.panel=document.createElement('aside');M.panel.className='pm25-region-panel';layout.appendChild(M.panel);}
  function updatePanel(show){ensurePanel();if(!M.panel)return;M.panel.style.display=show?'block':'none';if(!show||!M.regional)return;const th=document.getElementById('langThBtn')?.classList.contains('active'),delta=deltas().dust;M.panel.innerHTML=`<div class="pm25-region-title">${th?'ค่าฝุ่น PM2.5 เฉลี่ยรายภาค':'Regional average PM2.5'} <span>(µg/m³)</span></div>${REG.map(r=>`<div class="pm25-region-row"><b style="color:${r.c}">${r.id}</b><span>${th?r.th:r.en}</span><strong style="color:${r.c};border-color:${r.c}">${M.regional[r.id]===null?'—':Math.max(0,M.regional[r.id]+delta).toFixed(1)}</strong></div>`).join('')}<div class="pm25-region-note">${th?'คำนวณจาก raster และปรับตาม PM2.5 Scenario':'Raster mean adjusted by PM2.5 scenario'}</div>`;}

  function styles(){const s=document.createElement('style');s.textContent=`#forestRiskScaleLabels{display:none!important}.map-region-layout{display:flex;gap:12px;align-items:stretch}.map-region-layout #mapWrap{flex:1;min-width:0}.pm25-region-panel{width:215px;flex:0 0 215px;background:#fff;border:1px solid #e9e4d6;border-radius:8px;padding:12px;box-shadow:0 1px 3px rgba(0,0,0,.05)}.pm25-region-title{font-size:11.5px;font-weight:700;margin-bottom:9px}.pm25-region-title span{color:#8a8f80}.pm25-region-row{display:grid;grid-template-columns:28px 1fr 52px;gap:6px;align-items:center;padding:6px 0;border-bottom:1px solid #f0ede1;font-size:10.5px}.pm25-region-row span{color:#6b7062}.pm25-region-row strong{text-align:center;border:1px solid;border-radius:5px;padding:4px;background:#fff}.pm25-region-note{font-size:9.5px;color:#8a8f80;line-height:1.4;margin-top:8px}@media(max-width:1200px){.map-region-layout{display:block}.pm25-region-panel{width:100%;margin-top:10px}}`;document.head.appendChild(s);}

  let timer;function schedule(){clearTimeout(timer);timer=setTimeout(updateMap,120);}
  document.addEventListener('click',e=>{if(e.target.closest('[data-action="setMapTab"],[data-action="setLang"]'))schedule();});
  document.addEventListener('change',e=>{if(e.target.matches('select[data-field="targetYear"],input[data-onchange="climateAbsolute"]'))schedule();});
  document.addEventListener('DOMContentLoaded',async()=>{styles();try{M.rasters={temp:await fetchGeoTiff('./assets/rasters/mean_temp_annual_tmd_1991-2020.tif','temperature'),rainfall:await fetchGeoTiff('./assets/rasters/rainfall_annual_tmd_1991-2020.tif','rainfall'),dust:await fetchGeoTiff('./assets/rasters/pm25_regional_2014-2024.tif','pm25')};M.baseline.temp=observedMedian(M.rasters.temp);M.baseline.rainfall=observedMedian(M.rasters.rainfall);M.baseline.dust=observedMedian(M.rasters.dust);calcRegional();M.ready=true;schedule();}catch(err){console.error('Scenario maps:',err);}});
})();